### ISSUE TITLE
Test single quotes vs. double quotes doesn't ruin match

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#202]
If the table var name and the field var name don't use the same types of quotes, they should still match. [Probably also need to get rid of `\`]

[For an example on how this can create issues, see https://github.com/plocket/docassemble-ALAutomatedTestingTests/issues/125]

**Comment by plocket** [comment]
I think the way to handle this is to change all double quotes to single quotes when we're matching table rows and fields (`scope.getMatchingRows()`)

**Comment by plocket** [comment]
Not _all_ quotes.

* For the table, change it only in the `var` and `trigger` columns. Possibly only at the start and end.
* For the fields, change it only at the start and end of... values in checkboxes?

Also, for the table var, look out for both just `"` and also `\"`. I think.

**Comment by plocket** [comment]
Trigger var comes out with single quotes in DOM, even if the var used in the interview has double quotes and even if the field itself has double quotes. That means for `trigger` we only need to normalize the story table. E.g:

```yml
code: |
  double_quote_dict["double_quote_key"]
---
# ...
fields:
  - Doubly quoted key: double_quote_dict["double_quote_key"]
    datatype: checkboxes
    choices:
      - 1: dq_one
      - 2: dq_two
```

results in DOM data of `double_quote_dict['double_quote_key']`
