### ISSUE TITLE
Security: Freeze both our and the dev's package with package-lock.json

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#614]
I thought we had this issue, but I can't find it. This will ensure fullest security so that the updating/lack of security of upstream packages doesn't affect our packages except when we deliberately update package-lock.json.

For our dev's repo we need to:
- create a file to store their package-lock.json
- use/copy that file to create the dev's package-lock.json in the action (instead of the package.json)

For us and for the dev: configure our repo and their repo (through our action) to install using the package-lock.json.

**Comment by plocket** [comment]
For copying a file from our own repository, possibly see `action_path` at https://docs.github.com/en/actions/learn-github-actions/contexts.

**Comment by plocket** [comment]
This little test in our action works in a dependent repo:
```yml
runs:
  using: "composite"
  steps:
    - name: make file
      run: |
        touch cucumber.js
        cat "${{ github.action_path }}/cucumber.js" > cucumber.js
        file=$(<"cucumber.js")
        echo $file
      shell: bash
```

Note: tmate can't access values of variables like `github.whatever` in your local terminal. E.g. `github.action_path`. It gets the error 'bad substitution'. Instead, you have to (in your action.yml) add an environment variable to contain that value and use it later. Something like:

```yml
    - run: echo "ACTION_PATH=${{ github.action_path }}" >> $GITHUB_ENV
      shell: bash
    - name: make file
      run: |
        touch cucumber.js
        cat "${ACTION_PATH}/cucumber.js" > cucumber.js
        file=$(<"cucumber.js")
        echo $file
      shell: bash
```
