### ISSUE TITLE
Test: `choices` with `group`

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#821]
With and without the usual `multiselect`, `object multiselect` (not yet working), and other datatypes.

```
mandatory: True
question: What is your favorite fruit?
fields:
  - Fruit: favorite_fruit
    datatype: multiselect
    choices:
      - label: Fuji Apple
        value: fuji_apple
        group: Apple
      - label: Red Delicious Apple
        value: red_delicious_apple
        group: Apple
      - label: Peach
        value: peach
        group: Other
      - label: Pear
        value: pear
        group: Other
```
