### ISSUE TITLE
Document de-duping pull/push combo workflow triggers

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#867]
Tell end users how to use both push and pull_request triggers without firing both events at the same time.

```yml
jobs:
  job_name:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
```

https://github.com/IHaskell/IHaskell/blob/60a750f5b038a17717609d8a40be0fafd69e1c35/.github/workflows/stack.yml#L37
