### ISSUE TITLE
De-dupe action triggers

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#869]
Implement this code:

```yml
jobs:
  job_name:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
```

https://github.com/IHaskell/IHaskell/blob/60a750f5b038a17717609d8a40be0fafd69e1c35/.github/workflows/stack.yml#L37

It could make a good example [for our users]. Is there a reason to test the event happening at the same time? There are plenty of non-pr times when we push, so we should see plenty of both triggers.
